name: ${project.name}
main: musician101.minetanks.spigot.SpigotMineTanks
version: ${project.version}
description: ${project.description}
author: Musician101

commands:
    minetanks:
        aliases: [mt]
        description: Base command the plugin.