package io.musician101.minetanks.forge.tank;

import io.musician101.minetanks.common.CommonReference.CommonCannons;
import io.musician101.minetanks.common.CommonReference.CommonCountries;
import io.musician101.minetanks.common.CommonReference.CommonEngines;
import io.musician101.minetanks.common.CommonReference.CommonRadios;
import io.musician101.minetanks.common.CommonReference.CommonTankTypes;
import io.musician101.minetanks.common.CommonReference.CommonTanks;
import io.musician101.minetanks.common.CommonReference.CommonTracks;
import io.musician101.minetanks.common.CommonReference.CommonTurrets;
import io.musician101.minetanks.common.tank.AbstractInfoStorage;
import io.musician101.minetanks.common.tank.Armor;
import io.musician101.minetanks.forge.tank.modules.ForgeEngine;
import io.musician101.minetanks.forge.tank.modules.ForgeModules;
import io.musician101.minetanks.forge.tank.modules.ForgeRadio;
import io.musician101.minetanks.forge.tank.modules.cannon.ForgeAutoLoader;
import io.musician101.minetanks.forge.tank.modules.cannon.ForgeCannon;
import io.musician101.minetanks.forge.tank.modules.tracks.ForgeTracks;
import io.musician101.minetanks.forge.tank.modules.turret.ForgeTurrets;

import java.util.List;


public class ForgeTanks extends AbstractInfoStorage<ForgeTank>
{
    private ForgeTanks()
    {
        super(
                // China Lights
                new ForgeTank(CommonTanks.WZ_132, ForgeCountries.getCountry(CommonCountries.CHINA), ForgeTankTypes.getTankType(CommonTankTypes.LIGHT), 1150, new Armor(50, 25, 20), 64, new ForgeModules(new ForgeCannon(CommonCannons._100_MM_60_100T, 43, 7.57), new ForgeEngine(CommonEngines.EIGHT_V135, ForgeTankTypes.getTankType(CommonTankTypes.LIGHT)), new ForgeRadio(CommonRadios.A_220A, ForgeTankTypes.getTankType(CommonTankTypes.LIGHT)), ForgeTracks.getTracks(CommonTracks.WZ_132), ForgeTurrets.getTurret(CommonTurrets.WZ_132))),
                // China Mediums
                new ForgeTank(CommonTanks.ONE_21, ForgeCountries.getCountry(CommonCountries.CHINA), ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM), 1950, new Armor(120, 80, 60), 56, new ForgeModules(new ForgeCannon(CommonCannons._122_MM_60_122T, 40, 9.6), new ForgeEngine(CommonEngines.TWELVE_150L7, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), new ForgeRadio(CommonRadios.A_220B, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), ForgeTracks.getTracks(CommonTracks.ONE_21), ForgeTurrets.getTurret(CommonTurrets.ONE_21))),
                // China Heavies
                new ForgeTank(CommonTanks.ONE_13, ForgeCountries.getCountry(CommonCountries.CHINA), ForgeTankTypes.getTankType(CommonTankTypes.HEAVY), 2300, new Armor(120, 90, 70), 50, new ForgeModules(new ForgeCannon(CommonCannons._122_MM_60_122T, 34, 10.45), new ForgeEngine(CommonEngines.V_2_54SC, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), new ForgeRadio(CommonRadios.A_220B, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), ForgeTracks.getTracks(CommonTracks.ONE_13), ForgeTurrets.getTurret(CommonTurrets.ONE_13))),
                // Czechoslovakian Mediums
                new ForgeTank(CommonTanks.TVP_T_50_51, ForgeCountries.getCountry(CommonCountries.CZECH), ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM), 1800, new Armor(65, 40, 30), 60, new ForgeModules(new ForgeAutoLoader(CommonCannons._100_MM_AK1, 48, 23.97, 1.5, 4), new ForgeEngine(CommonEngines.PRAGA_AXK, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), new ForgeRadio(CommonRadios.RADIOSTANICE_RM_31T, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), ForgeTracks.getTracks(CommonTracks.TVP_T_50_51), ForgeTurrets.getTurret(CommonTurrets.TVP_T_50_51))),
                // France Lights
                new ForgeTank(CommonTanks.AMX_13_90, ForgeCountries.getCountry(CommonCountries.FRANCE), ForgeTankTypes.getTankType(CommonTankTypes.LIGHT), 1100, new Armor(40, 20, 15), 64, new ForgeModules(new ForgeAutoLoader(CommonCannons._90_MM_F3, 36, 42, 2.73, 6), new ForgeEngine(CommonEngines.DETROIT_DIESEL_6V53T_S, ForgeTankTypes.getTankType(CommonTankTypes.LIGHT)), new ForgeRadio(CommonRadios.SCR_528, ForgeTankTypes.getTankType(CommonTankTypes.LIGHT)), ForgeTracks.getTracks(CommonTracks.AMX_13_TYPE_2D), ForgeTurrets.getTurret(CommonTurrets.FL_10_TYPE_D))),
                // French Mediums
                new ForgeTank(CommonTanks.BAT_CHAT_25_T, ForgeCountries.getCountry(CommonCountries.FRANCE), ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM), 1800, new Armor(60, 40, 30), 65, new ForgeModules(new ForgeAutoLoader(CommonCannons._105_MM_MLE_57, 30, 40, 2.73, 5), new ForgeEngine(CommonEngines.HISPANO_SUIZA_HS_110, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), new ForgeRadio(CommonRadios.SCR_528F, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), ForgeTracks.getTracks(CommonTracks.BAT_CHAT_25_T), ForgeTurrets.getTurret(CommonTurrets.BAT_CHAT_25_T))),
                new ForgeTank(CommonTanks.AMX_30_B, ForgeCountries.getCountry(CommonCountries.FRANCE), ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM), 1900, new Armor(80, 35, 30), 65, new ForgeModules(new ForgeCannon(CommonCannons._105_MM_MLE_F1, 50, 8.53), new ForgeEngine(CommonEngines.HISPANO_SUIZA_HS_110, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), new ForgeRadio(CommonRadios.TRVP_13_A, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), ForgeTracks.getTracks(CommonTracks.AMX_30_B), ForgeTurrets.getTurret(CommonTurrets.AMX_30_B))),
                //French Heavies
                new ForgeTank(CommonTanks.AMX_50_B, ForgeCountries.getCountry(CommonCountries.FRANCE), ForgeTankTypes.getTankType(CommonTankTypes.HEAVY), 2100, new Armor(170, 30, 30), 65, new ForgeModules(new ForgeAutoLoader(CommonCannons._120_MM_SA46, 56, 30, 2.5, 4), new ForgeEngine(CommonEngines.MAYBACH_HL_295_F, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), new ForgeRadio(CommonRadios.SCR_619, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), ForgeTracks.getTracks(CommonTracks.AMX_50_B), ForgeTurrets.getTurret(CommonTurrets.AMX_50_B))),
                //French TDs
                new ForgeTank(CommonTanks.AMX_50_FOCH_155, ForgeCountries.getCountry(CommonCountries.FRANCE), ForgeTankTypes.getTankType(CommonTankTypes.TD), 1850, new Armor(180, 40, 40), 50, new ForgeModules(new ForgeAutoLoader(CommonCannons._155_MM_AC_SA58, 30, 47.94, 5, 3), new ForgeEngine(CommonEngines.SAURER, ForgeTankTypes.getTankType(CommonTankTypes.TD)), new ForgeRadio(CommonRadios.SCR_619, ForgeTankTypes.getTankType(CommonTankTypes.TD)), ForgeTracks.getTracks(CommonTracks.AMX_50_FOCH_155), ForgeTurrets.getTurret(CommonTurrets.NONE_TD))),
                //French Arty
                new ForgeTank(CommonTanks.BAT_CHAT_155_58, ForgeCountries.getCountry(CommonCountries.FRANCE), ForgeTankTypes.getTankType(CommonTankTypes.SPG), 490, new Armor(50, 30, 20), 62, new ForgeModules(new ForgeAutoLoader(CommonCannons.CANNON_DE_155_MM, 36, 76.71, 6, 4), new ForgeEngine(CommonEngines.HISPANO_SUIZA_HS_110, ForgeTankTypes.getTankType(CommonTankTypes.SPG)), new ForgeRadio(CommonRadios.SCR_528F, ForgeTankTypes.getTankType(CommonTankTypes.SPG)), ForgeTracks.getTracks(CommonTracks.BAT_CHAT_155_58), ForgeTurrets.getTurret(CommonTurrets.NONE_SPG))),
                //German Lights
                new ForgeTank(CommonTanks.SPAHPANZER_RU_251, ForgeCountries.getCountry(CommonCountries.GERMANY), ForgeTankTypes.getTankType(CommonTankTypes.LIGHT), 500, new Armor(25, 20, 8), 80, new ForgeModules(new ForgeCannon(CommonCannons._90_MM_RHEINMETALL_DM1, 41, 5.94), new ForgeEngine(CommonEngines.MB_837_EA_600, ForgeTankTypes.getTankType(CommonTankTypes.LIGHT)), new ForgeRadio(CommonRadios.AN_GRC_7, ForgeTankTypes.getTankType(CommonTankTypes.LIGHT)), ForgeTracks.getTracks(CommonTracks.SPAHPANZER_RU_251_PT_II), ForgeTurrets.getTurret(CommonTurrets.SPAHPANZER_RU_251))),
                //German Mediums
                new ForgeTank(CommonTanks.E_50_M, ForgeCountries.getCountry(CommonCountries.GERMANY), ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM), 2050, new Armor(150, 80, 80), 60, new ForgeModules(new ForgeCannon(CommonCannons._10_5_CM_KWK_L52_AUSF_K, 48, 9.2), new ForgeEngine(CommonEngines.MAYBACH_HL_235, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), new ForgeRadio(CommonRadios.TEN_WSC, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), ForgeTracks.getTracks(CommonTracks.E_50_M), ForgeTurrets.getTurret(CommonTurrets.E_50_M))),
                new ForgeTank(CommonTanks.LEOPARD_1, ForgeCountries.getCountry(CommonCountries.GERMANY), ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM), 1950, new Armor(70, 35, 25), 65, new ForgeModules(new ForgeCannon(CommonCannons._10_5_CM_BORDKANONE_L7A3, 60, 8.34), new ForgeEngine(CommonEngines.MTU_MB_838_CAM_500A, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), new ForgeRadio(CommonRadios.SEM_25A, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), ForgeTracks.getTracks(CommonTracks.LEOPARD_1), ForgeTurrets.getTurret(CommonTurrets.LEOPARD_1))),
                //German Heavies
                new ForgeTank(CommonTanks.E_100, ForgeCountries.getCountry(CommonCountries.GERMANY), ForgeTankTypes.getTankType(CommonTankTypes.HEAVY), 2700, new Armor(200, 120, 150), 30, new ForgeModules(new ForgeCannon(CommonCannons._15_CM_KWK_L38, 50, 19.18), new ForgeEngine(CommonEngines.MAYBACH_NEUES_PROJEKT, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), new ForgeRadio(CommonRadios.TEN_WSC, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), ForgeTracks.getTracks(CommonTracks.E_100), ForgeTurrets.getTurret(CommonTurrets.E_100))),
                new ForgeTank(CommonTanks.MAUS, ForgeCountries.getCountry(CommonCountries.GERMANY), ForgeTankTypes.getTankType(CommonTankTypes.HEAVY), 3000, new Armor(200, 185, 160), 20, new ForgeModules(new ForgeCannon(CommonCannons._12_8_CM_KWK_44_L55, 68, 14.29), new ForgeEngine(CommonEngines.DB_603_A2, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), new ForgeRadio(CommonRadios.TEN_WSC, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), ForgeTracks.getTracks(CommonTracks.MAUS), ForgeTurrets.getTurret(CommonTurrets.MAUS))),
                new ForgeTank(CommonTanks.VK_7201, ForgeCountries.getCountry(CommonCountries.GERMANY), ForgeTankTypes.getTankType(CommonTankTypes.HEAVY), 2500, new Armor(200, 160, 120), 43, new ForgeModules(new ForgeCannon("15 cm Kw.K L/38", 24, 21.09), new ForgeEngine(CommonEngines.MB_517, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), new ForgeRadio(CommonRadios.TEN_WSC, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), ForgeTracks.getTracks(CommonTracks.VK_7201), ForgeTurrets.getTurret(CommonTurrets.VK_7201))),
                //German TDs
                new ForgeTank(CommonTanks.JAGDPANZER_E_100, ForgeCountries.getCountry(CommonCountries.GERMANY), ForgeTankTypes.getTankType(CommonTankTypes.TD), 2200, new Armor(200, 120, 150), 30, new ForgeModules(new ForgeCannon(CommonCannons._17_CM_PAK, 24, 24.64), new ForgeEngine(CommonEngines.MAYBACH_NEUES_PROJEKT, ForgeTankTypes.getTankType(CommonTankTypes.TD)), new ForgeRadio(CommonRadios.TEN_WSC, ForgeTankTypes.getTankType(CommonTankTypes.TD)), ForgeTracks.getTracks(CommonTracks.JAGDPANZER_E_100), ForgeTurrets.getTurret(CommonTurrets.NONE_TD))),
                new ForgeTank(CommonTanks.WAFFENTRAGER_E_100, ForgeCountries.getCountry(CommonCountries.GERMANY), ForgeTankTypes.getTankType(CommonTankTypes.TD), 2000, new Armor(200, 120, 150), 40, new ForgeModules(new ForgeAutoLoader(CommonCannons._15_CM_PAK_L38, 60, 57.94, 3, 4), new ForgeEngine(CommonEngines.MAYBACH_NEUES_PROJEKT, ForgeTankTypes.getTankType(CommonTankTypes.TD)), new ForgeRadio(CommonRadios.TEN_WSC, ForgeTankTypes.getTankType(CommonTankTypes.TD)), ForgeTracks.getTracks(CommonTracks.WAFFENTRAGER_E_100), ForgeTurrets.getTurret(CommonTurrets.WAFFENTRAGER_E_100))),
                //German Arty
                new ForgeTank(CommonTanks.GW_E_100, ForgeCountries.getCountry(CommonCountries.GERMANY), ForgeTankTypes.getTankType(CommonTankTypes.SPG), 550, new Armor(80, 50, 40), 40, new ForgeModules(new ForgeCannon(CommonCannons._21_CM_MORSER_18_2, 30, 40.75), new ForgeEngine(CommonEngines.MAYBACH_HL_234, ForgeTankTypes.getTankType(CommonTankTypes.SPG)), new ForgeRadio(CommonRadios.TEN_WSC, ForgeTankTypes.getTankType(CommonTankTypes.SPG)), ForgeTracks.getTracks(CommonTracks.GW_E_100), ForgeTurrets.getTurret(CommonTurrets.NONE_SPG))),
                //Japanese Mediums
                new ForgeTank(CommonTanks.STB_1, ForgeCountries.getCountry(CommonCountries.JAPAN), ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM), 1950, new Armor(110, 35, 25), 53, new ForgeModules(new ForgeCannon(CommonCannons._105_MM_RIFLED_GUN, 50, 7.67), new ForgeEngine(CommonEngines.MITSUBISHI_10ZF21WT, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), new ForgeRadio(CommonRadios.TYPE_67, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), ForgeTracks.getTracks(CommonTracks.STB_1), ForgeTurrets.getTurret(CommonTurrets.STB_1))),
                //Japanese Heavies
                new ForgeTank(CommonTanks.TYPE_5_HEAVY, ForgeCountries.getCountry(CommonCountries.JAPAN), ForgeTankTypes.getTankType(CommonTankTypes.HEAVY), 2800, new Armor(260, 140, 150), 25, new ForgeModules(new ForgeCannon(CommonCannons._14_CM_50_3RD_YEAR_TYPE, 60, 16.97), new ForgeEngine(CommonEngines.KAWASAKI_TYPE_98, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), new ForgeRadio(CommonRadios.TYPE_3_KO, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), ForgeTracks.getTracks(CommonTracks.TYPE_5_HEAVY), ForgeTurrets.getTurret(CommonTurrets.TYPE_5_HEAVY))),
                //British Mediums
                new ForgeTank(CommonTanks.FV4202, ForgeCountries.getCountry(CommonCountries.UK), ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM), 1950, new Armor(121, 51, 32), 40, new ForgeModules(new ForgeCannon(CommonCannons._105_MM_ROYAL_ORDNANCE_L7A1, 72, 8.25), new ForgeEngine(CommonEngines.ROLLS_ROYCE_METEOR_M120A, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), new ForgeRadio(CommonRadios.SR_C45, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), ForgeTracks.getTracks(CommonTracks.FV4202), ForgeTurrets.getTurret(CommonTurrets.FV4202))),
                //British Heavies
                new ForgeTank(CommonTanks.FV215B, ForgeCountries.getCountry(CommonCountries.UK), ForgeTankTypes.getTankType(CommonTankTypes.HEAVY), 2500, new Armor(152.4, 101.6, 76.2), 34, new ForgeModules(new ForgeCannon(CommonCannons._120_MM_GUN_L1A1, 35, 8.34), new ForgeEngine(CommonEngines.ROLLS_ROYCE_GRIFFON, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), new ForgeRadio(CommonRadios.SR_C45, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), ForgeTracks.getTracks(CommonTracks.FV215), ForgeTurrets.getTurret(CommonTurrets.FV215))),
                //British TDs
                new ForgeTank(CommonTanks.FV215B_183, ForgeCountries.getCountry(CommonCountries.UK), ForgeTankTypes.getTankType(CommonTankTypes.TD), 2000, new Armor(152.4, 50.8, 76.2), 34, new ForgeModules(new ForgeCannon(CommonCannons._183_MM_L4, 12, 28.77), new ForgeEngine(CommonEngines.ROLLS_ROYCE_METEOR_MK_12, ForgeTankTypes.getTankType(CommonTankTypes.TD)), new ForgeRadio(CommonRadios.SR_C45, ForgeTankTypes.getTankType(CommonTankTypes.TD)), ForgeTracks.getTracks(CommonTracks.FV215B), ForgeTurrets.getTurret(CommonTurrets.FV215B))),
                new ForgeTank(CommonTanks.FV4005_STAGE_II, ForgeCountries.getCountry(CommonCountries.UK), ForgeTankTypes.getTankType(CommonTankTypes.TD), 1850, new Armor(76.2, 50.8, 38.1), 35, new ForgeModules(new ForgeCannon(CommonCannons._183_MM_L4, 12, 28.77), new ForgeEngine(CommonEngines.ROLLS_ROYCE_METEOR_MK_IVB, ForgeTankTypes.getTankType(CommonTankTypes.TD)), new ForgeRadio(CommonRadios.SR_C45, ForgeTankTypes.getTankType(CommonTankTypes.TD)), ForgeTracks.getTracks(CommonTracks.FV4005_STAGE_II), ForgeTurrets.getTurret(CommonTurrets.FV4005_STAGE_II))),
                //British Arty
                new ForgeTank(CommonTanks.CONQUEROR_GC, ForgeCountries.getCountry(CommonCountries.UK), ForgeTankTypes.getTankType(CommonTankTypes.SPG), 530, new Armor(152.4, 50.8, 76.2), 34, new ForgeModules(new ForgeCannon(CommonCannons.BL_9_2_IN_HOWITZER, 24, 55.71), new ForgeEngine(CommonEngines.ROLLS_ROYCE_METEOR_M120, ForgeTankTypes.getTankType(CommonTankTypes.SPG)), new ForgeRadio(CommonRadios.SR_C45, ForgeTankTypes.getTankType(CommonTankTypes.SPG)), ForgeTracks.getTracks(CommonTracks.CONQUEROR_GUN_CARRIAGE), ForgeTurrets.getTurret(CommonTurrets.NONE_SPG))),
                //American Lights
                new ForgeTank(CommonTanks.T49, ForgeCountries.getCountry(CommonCountries.USA), ForgeTankTypes.getTankType(CommonTankTypes.LIGHT), 1000, new Armor(25.4, 25.4, 19.1), 72, new ForgeModules(new ForgeCannon(CommonCannons._90_MM_GUN_T185, 22, 22.05), new ForgeEngine(CommonEngines.CONTINENTAL_AOI_895_5, ForgeTankTypes.getTankType(CommonTankTypes.LIGHT)), new ForgeRadio(CommonRadios.AN_GRC_7, ForgeTankTypes.getTankType(CommonTankTypes.LIGHT)), ForgeTracks.getTracks(CommonTracks.XM551_TEST_BED), ForgeTurrets.getTurret(CommonTurrets.XM551_TEST_BED))),
                //American Mediums
                new ForgeTank(CommonTanks.M48A1_PATTON, ForgeCountries.getCountry(CommonCountries.USA), ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM), 2000, new Armor(152.4, 76.2, 38.1), 45, new ForgeModules(new ForgeCannon(CommonCannons._105_MM_GUN_M68, 57, 8.44), new ForgeEngine(CommonEngines.CONTINENTAL_AV_1790_7B, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), new ForgeRadio(CommonRadios.AN_VRC_7, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), ForgeTracks.getTracks(CommonTracks.T97E2), ForgeTurrets.getTurret(CommonTurrets.M87))),
                new ForgeTank(CommonTanks.M60, ForgeCountries.getCountry(CommonCountries.USA), ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM), 2000, new Armor(93.2, 73.7, 25.4), 48, new ForgeModules(new ForgeCannon(CommonCannons._105_MM_GUN_M68, 57, 8.44), new ForgeEngine(CommonEngines.CONTINENTAL_AVDS_1790_2, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), new ForgeRadio(CommonRadios.AN_VRC_12, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), ForgeTracks.getTracks(CommonTracks.M60), ForgeTurrets.getTurret(CommonTurrets.M60))),
                //American Heavies
                new ForgeTank(CommonTanks.T110E5, ForgeCountries.getCountry(CommonCountries.USA), ForgeTankTypes.getTankType(CommonTankTypes.HEAVY), 2200, new Armor(254, 76.2, 38.1), 37, new ForgeModules(new ForgeCannon(CommonCannons._120_MM_GUN_M58, 42, 9.59), new ForgeEngine(CommonEngines.CONTINENTAL_AOI_1490, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), new ForgeRadio(CommonRadios.AN_VRC_3, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), ForgeTracks.getTracks(CommonTracks.T110E27), ForgeTurrets.getTurret(CommonTurrets.T53))),
                new ForgeTank(CommonTanks.T57, ForgeCountries.getCountry(CommonCountries.USA), ForgeTankTypes.getTankType(CommonTankTypes.HEAVY), 2250, new Armor(203, 50.8, 38.1), 35, new ForgeModules(new ForgeAutoLoader(CommonCannons._120_MM_GUN_T179, 36, 23.97, 2, 4), new ForgeEngine(CommonEngines.CONTINENTAL_AV_1790_5C, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), new ForgeRadio(CommonRadios.AN_VRC_3, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), ForgeTracks.getTracks(CommonTracks.T97), ForgeTurrets.getTurret(CommonTurrets.T169))),
                //American TDs
                new ForgeTank(CommonTanks.T110E3, ForgeCountries.getCountry(CommonCountries.USA), ForgeTankTypes.getTankType(CommonTankTypes.TD), 2050, new Armor(305, 76, 38), 30, new ForgeModules(new ForgeCannon(CommonCannons._155_MM_AT_GUN_T7E2, 27, 16.3), new ForgeEngine(CommonEngines.CONTINENTAL_AOI_1490, ForgeTankTypes.getTankType(CommonTankTypes.TD)), new ForgeRadio(CommonRadios.AN_VRC_3, ForgeTankTypes.getTankType(CommonTankTypes.TD)), ForgeTracks.getTracks(CommonTracks.T110E3), ForgeTurrets.getTurret(CommonTurrets.NONE_TD))),
                new ForgeTank(CommonTanks.T110E4, ForgeCountries.getCountry(CommonCountries.USA), ForgeTankTypes.getTankType(CommonTankTypes.TD), 2000, new Armor(260, 76, 38), 35, new ForgeModules(new ForgeCannon(CommonCannons._155_MM_AT_GUN_T7E2, 27, 18.7), new ForgeEngine(CommonEngines.CONTINENTAL_AOI_1490, ForgeTankTypes.getTankType(CommonTankTypes.TD)), new ForgeRadio(CommonRadios.AN_VRC_3, ForgeTankTypes.getTankType(CommonTankTypes.TD)), ForgeTracks.getTracks(CommonTracks.T110E4), ForgeTurrets.getTurret(CommonTurrets.T110E4))),
                //American Arty
                new ForgeTank(CommonTanks.T92, ForgeCountries.getCountry(CommonCountries.USA), ForgeTankTypes.getTankType(CommonTankTypes.SPG), 500, new Armor(25.4, 25.4, 21.7), 32, new ForgeModules(new ForgeCannon(CommonCannons._240_MM_HOWITZER, 16, 50.82), new ForgeEngine(CommonEngines.FORD_GAF_T92, ForgeTankTypes.getTankType(CommonTankTypes.SPG)), new ForgeRadio(CommonRadios.SCR_528A, ForgeTankTypes.getTankType(CommonTankTypes.SPG)), ForgeTracks.getTracks(CommonTracks.T92_T80E1), ForgeTurrets.getTurret(CommonTurrets.NONE_SPG))),
                //Russian Lights
                new ForgeTank(CommonTanks.T_54_LTWT, ForgeCountries.getCountry(CommonCountries.USSR), ForgeTankTypes.getTankType(CommonTankTypes.LIGHT), 1250, new Armor(80, 60, 45), 69, new ForgeModules(new ForgeCannon(CommonCannons._100_MM_D10T, 34, 7.19), new ForgeEngine(CommonEngines.V_14, ForgeTankTypes.getTankType(CommonTankTypes.LIGHT)), new ForgeRadio(CommonRadios.TEN_RT_26, ForgeTankTypes.getTankType(CommonTankTypes.LIGHT)), ForgeTracks.getTracks(CommonTracks.T_54_ENHANCED_LTWT_VERSION), ForgeTurrets.getTurret(CommonTurrets.T_54_LTWT_VERSION))),
                //Russian Mediums
                new ForgeTank(CommonTanks.OBJECT_140, ForgeCountries.getCountry(CommonCountries.USSR), ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM), 1900, new Armor(100, 80, 55), 40, new ForgeModules(new ForgeCannon(CommonCannons._100_MM_8TS, 50, 6.33), new ForgeEngine(CommonEngines.TD_12, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), new ForgeRadio(CommonRadios.R_113M, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), ForgeTracks.getTracks(CommonTracks.OBJECT_140), ForgeTurrets.getTurret(CommonTurrets.OBJECT_140))),
                new ForgeTank(CommonTanks.OBJECT_430, ForgeCountries.getCountry(CommonCountries.USSR), ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM), 1900, new Armor(120, 80, 40), 55, new ForgeModules(new ForgeCannon(CommonCannons._100_MM_8TS, 50, 6.14), new ForgeEngine(CommonEngines.FIVE_TD, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), new ForgeRadio(CommonRadios.R_113M, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), ForgeTracks.getTracks(CommonTracks.OBJECT_430), ForgeTurrets.getTurret(CommonTurrets.OBJECT_430))),
                new ForgeTank(CommonTanks.OBJECT_907, ForgeCountries.getCountry(CommonCountries.USSR), ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM), 2000, new Armor(100, 85, 45), 55, new ForgeModules(new ForgeCannon(CommonCannons._100_MM_D_54TS, 45, 6.23), new ForgeEngine(CommonEngines.V_12_5U, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), new ForgeRadio(CommonRadios.R_123, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), ForgeTracks.getTracks(CommonTracks.OBJECT_907), ForgeTurrets.getTurret(CommonTurrets.OBJECT_907))),
                new ForgeTank(CommonTanks.T_62A, ForgeCountries.getCountry(CommonCountries.USSR), ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM), 1950, new Armor(100, 80, 45), 50, new ForgeModules(new ForgeCannon(CommonCannons._100_MM_8TS, 50, 6.33), new ForgeEngine(CommonEngines.V_55, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), new ForgeRadio(CommonRadios.R_123, ForgeTankTypes.getTankType(CommonTankTypes.MEDIUM)), ForgeTracks.getTracks(CommonTracks.T_62A), ForgeTurrets.getTurret(CommonTurrets.T_62))),
                //Russian Heavies
                new ForgeTank(CommonTanks.IS_4, ForgeCountries.getCountry(CommonCountries.USSR), ForgeTankTypes.getTankType(CommonTankTypes.HEAVY), 2500, new Armor(140, 160, 100), 43, new ForgeModules(new ForgeCannon(CommonCannons._122_MM_M62_T2, 30, 11.51), new ForgeEngine(CommonEngines.V_12, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), new ForgeRadio(CommonRadios.TEN_RK_26, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), ForgeTracks.getTracks(CommonTracks.IS_4M), ForgeTurrets.getTurret(CommonTurrets.IS_4M))),
                new ForgeTank(CommonTanks.IS_7, ForgeCountries.getCountry(CommonCountries.USSR), ForgeTankTypes.getTankType(CommonTankTypes.HEAVY), 2150, new Armor(150, 150, 100), 60, new ForgeModules(new ForgeCannon(CommonCannons._130_MM_S_70, 30, 13.14), new ForgeEngine(CommonEngines.M_50T, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), new ForgeRadio(CommonRadios.TEN_RK_26, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), ForgeTracks.getTracks(CommonTracks.IS_7), ForgeTurrets.getTurret(CommonTurrets.IS_7))),
                new ForgeTank(CommonTanks.OBJECT_260, ForgeCountries.getCountry(CommonCountries.USSR), ForgeTankTypes.getTankType(CommonTankTypes.HEAVY), 2100, new Armor(150, 150, 70), 60, new ForgeModules(new ForgeCannon(CommonCannons._122_MM_BL_13_1, 30, 11.03), new ForgeEngine(CommonEngines.TWO_X_V_16, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), new ForgeRadio(CommonRadios.TEN_RK_26, ForgeTankTypes.getTankType(CommonTankTypes.HEAVY)), ForgeTracks.getTracks(CommonTracks.OBJECT_260_MOD_1945), ForgeTurrets.getTurret(CommonTurrets.OBJECT_260_MOD_1945))),
                //Russian TDs
                new ForgeTank(CommonTanks.OBJECT_263, ForgeCountries.getCountry(CommonCountries.USSR), ForgeTankTypes.getTankType(CommonTankTypes.TD), 1900, new Armor(250, 80, 50), 55, new ForgeModules(new ForgeCannon(CommonCannons._130_MM_S_70A, 42, 10.26), new ForgeEngine(CommonEngines.M_50T, ForgeTankTypes.getTankType(CommonTankTypes.TD)), new ForgeRadio(CommonRadios.TEN_RK_26, ForgeTankTypes.getTankType(CommonTankTypes.TD)), ForgeTracks.getTracks(CommonTracks.OBJECT_263), ForgeTurrets.getTurret(CommonTurrets.NONE_TD))),
                new ForgeTank(CommonTanks.OBJECT_268, ForgeCountries.getCountry(CommonCountries.USSR), ForgeTankTypes.getTankType(CommonTankTypes.TD), 1950, new Armor(187, 100, 50), 48, new ForgeModules(new ForgeCannon(CommonCannons._152_MM_M64, 35, 15.82), new ForgeEngine(CommonEngines.V_16FN, ForgeTankTypes.getTankType(CommonTankTypes.TD)), new ForgeRadio(CommonRadios.R_113M, ForgeTankTypes.getTankType(CommonTankTypes.TD)), ForgeTracks.getTracks(CommonTracks.OBJECT_268), ForgeTurrets.getTurret(CommonTurrets.NONE_TD))),
                //Russian Arty
                new ForgeTank(CommonTanks.OBJECT_261, ForgeCountries.getCountry(CommonCountries.USSR), ForgeTankTypes.getTankType(CommonTankTypes.SPG), 510, new Armor(75, 50, 30), 50, new ForgeModules(new ForgeCannon(CommonCannons._180_MM_B_1_P, 18, 33.56), new ForgeEngine(CommonEngines.M_50T, ForgeTankTypes.getTankType(CommonTankTypes.SPG)), new ForgeRadio(CommonRadios.TEN_RK_26, ForgeTankTypes.getTankType(CommonTankTypes.SPG)), ForgeTracks.getTracks(CommonTracks.OBJECT_261), ForgeTurrets.getTurret(CommonTurrets.NONE_SPG))));
    }


    public static ForgeTank getTank(String name)
    {
        return new ForgeTanks().get(name);
    }

    public static List<ForgeTank> getValues()
    {
        return new ForgeTanks().values();
    }
}
